---
name: Setup Go.
description: Setup Go.

inputs:
  go_version:
    description: The Go version.
    required: false
    default: '1.19'

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go_version }}
    - name: Setup GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        install-only: true
